stages:
  - lint
  - test
  - build

variables:
  GO_VERSION: "1.22"
  GOLANGCI_LINT_IMAGE: "golangci/golangci-lint:v2.11.3"

default:
  interruptible: true

lint:
  stage: lint
  image: $GOLANGCI_LINT_IMAGE
  script:
    - golangci-lint version
    - golangci-lint run ./...
  cache:
    key: golangci-lint-cache
    paths:
      - /root/.cache/golangci-lint

unit-tests:
  stage: test
  image: golang:${GO_VERSION}
  before_script:
    - go version
    - go mod download
  script:
    - go test -race -count=100 ./...
  cache:
    key: go-test-cache
    paths:
      - /go/pkg/mod
      - /root/.cache/go-build

build:
  stage: build
  image: golang:${GO_VERSION}
  before_script:
    - go version
    - go mod download
  script:
    - mkdir -p bin
    - go build -o ./bin/antibf ./cmd/antibf
  artifacts:
    paths:
      - bin/antibf
    expire_in: 1 week
  cache:
    key: go-build-cache
    paths:
      - /go/pkg/mod
      - /root/.cache/go-build